---
# Docker compose with overrides and config to run in AWS ECS

version: "3.9"
networks:
  public:
    x-vpc: PublicSubnets
  private:
    x-vpc: AppSubnets
  db:
    x-vpc: StorageSubnets

secrets:
  sandboxsecrets:
    x-secrets:
      Name: SandboxAppConfiguration
      JsonKeys:
        - SecretKey: GNR_ROOTPWD
          VarName: GNR_ROOTPWD
        - SecretKey: GNR_DB_IMPLEMENTATION
          VarName: GNR_DB_IMPLEMENTATION
        - SecretKey: GNR_DB_HOST
          VarName: GNR_DB_HOST
        - SecretKey: GNR_DB_NAME
          VarName: GNR_DB_NAME
        - SecretKey: GNR_DB_USER
          VarName: GNR_DB_USER
        - SecretKey: GNR_DB_PORT
          VarName: GNR_DB_PORT
        - SecretKey: GNR_DB_PASSWORD
          VarName: GNR_DB_PASSWORD
        - SecretKey: GNR_LOCALE
          VarName: GNR_LOCALE
        - SecretKey: GNR_MAINPACKAGE
          VarName: GNR_MAINPACKAGE

x-rds:
  rdsmain:
    Lookup:
      db:
        Name: rdsmain
        Tags:
          - name: rdsmain
    Services:
      sandbox:
        Access: RW

x-vpc:
  Lookup:
    VpcId:
      Tags:
        - Name: mainvpc
    AppSubnets:
      Tags:
        - vpc::usage: application
    StorageSubnets:
      Tags:
        - vpc::usage: storage
    PublicSubnets:
      Tags:
        - vpc::usage: public

services:
  sandbox:
    image: ghcr.io/genropy/sandbox:develop
    ports:
      - "8888:8888"
      - "9999:9999"
    labels:
      traefik.enable: "true"
      traefik.http.routers.sandbox_gunicorn.rule: "(Host(`sandbox.gnr.world`)&& !Path(`/websocket`))"
      traefik.http.routers.sandbox_gunicorn.entrypoints: web
      traefik.http.routers.sandbox_gunicorn.service: snd_gunicorn
      traefik.http.services.snd_gunicorn.loadbalancer.server.port: 8888
      traefik.http.routers.sandbox_tornado.rule: "(Host(`sandbox.gnr.world`) && Path(`/websocket`))"
      traefik.http.routers.sandbox_tornado.entrypoints: web
      traefik.http.routers.sandbox_tornado.service: snd_tornado
      traefik.http.services.snd_tornado.loadbalancer.server.port: 9999 # Override for your real domain name for this service.
    deploy:
      resources:
        reservations:
          cpus: 0.5
          memory: 512MB
        limits:
          cpus: 1.5
          memory: 2048MB
    networks:
      private: {}
      db: {}
    secrets:
      - sandboxsecrets
    x-network:
      Ingress:
        ExtSources:
          - IPv4: 0.0.0.0/0
            Name: ANY
            Description: ANY
        Myself: True
    x-ecs:
      EnableExecuteCommand: true
    deploy:
      resources:
        reservations:
          cpus: 0.5
          memory: 512MB
        limits:
          cpus: 1.5
          memory: 2048MB
#    x-network:
#      Ingress:
#        Services:
#          - Name: traefik

x-cluster:
  Lookup:
    Tags:
      - name: main
    ClusterName: main

x-route53:
  PublicZone:
    Name: gnr.world
    Lookup: true

x-tags:
  cliente: sandbox