name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: genropy/actions@develop
        with:
          image_name: sandbox
          instance_name: sandboxpg
          github_token: ${{ secrets.GITHUB_TOKEN }}
